// flow-typed signature: 8f63b807651f8288c751669dcefbc02b
// flow-typed version: <<STUB>>/react-select2-wrapper_v^1.0.4-beta5/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-select2-wrapper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-select2-wrapper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-select2-wrapper/lib/components/Select2' {
  declare module.exports: any;
}

declare module 'react-select2-wrapper/src/components/Select2' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-select2-wrapper/lib/components/Select2.js' {
  declare module.exports: $Exports<'react-select2-wrapper/lib/components/Select2'>;
}
declare module 'react-select2-wrapper/src/components/Select2.js' {
  declare module.exports: $Exports<'react-select2-wrapper/src/components/Select2'>;
}
